# Makefile for Sphinx documentation
# This file is generated by the Sphinx documentation tool

# Python interpreter path (using your virtual environment)
PYTHON = ~/.virtualenvs/app/bin/python
SPHINXBUILD = $(PYTHON) -m sphinx
SOURCEDIR = source
BUILDDIR = build

# The default target
.PHONY: help clean html latexpdf

help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo "  html       to make standalone HTML files"
	@echo "  latexpdf   to make LaTeX files and run them through pdflatex"
	@echo "  clean      to remove generated files"
	@echo "  help       to show this help message"

clean:
	rm -rf $(BUILDDIR)/*
	@echo "Cleaned build directory"

html:
	$(SPHINXBUILD) -b html $(SOURCEDIR) $(BUILDDIR)/html
	@echo "Build finished. The HTML pages are in $(BUILDDIR)/html."

latexpdf:
	$(SPHINXBUILD) -b latex $(SOURCEDIR) $(BUILDDIR)/latex
	cd $(BUILDDIR)/latex && make
	@echo "Build finished. The PDF files are in $(BUILDDIR)/latex."

# Additional targets for common documentation tasks
.PHONY: clean-all
clean-all: clean
	rm -rf $(BUILDDIR)
	@echo "Cleaned all build artifacts"

.PHONY: serve
serve:
	$(SPHINXBUILD) -b html $(SOURCEDIR) $(BUILDDIR)/html
	cd $(BUILDDIR)/html && python -m http.server 8000
	@echo "Documentation server running at http://localhost:8000"

# More robust version with better dependency checking
.PHONY: check-deps
check-deps:
	@echo "Checking dependencies..."
	@if ! $(PYTHON) -c "import sphinx" >/dev/null 2>&1; then \
		echo "Error: Sphinx not found in virtual environment"; \
		echo "Make sure you're in the correct virtual environment"; \
		exit 1; \
	fi
	@echo "✓ Sphinx found in virtual environment"
	@if [ -z "$(LATEX_CHECK)" ] || [ -z "$(PDFLATEX_CHECK)" ]; then \
		echo "Warning: LaTeX tools not found. Required for PDF generation."; \
		echo "Install with: sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"; \
	else \
		echo "✓ LaTeX tools found"; \
	fi
	@echo "Dependencies check completed"

.PHONY: install-deps
install-deps:
	$(PYTHON) -m pip install sphinx sphinx-rtd-theme
	@echo "Sphinx dependencies installed"

# Default target
default: html
